
---
- name: Deploy qubinode custom kickstart files
  become: yes
  template:
    src:  "{{ ks_file }}.j2"
    dest: "/root/usb_stick/ks.cfg"
    mode: '0644'

- name: Deploy isolinux config file
  become: yes
  template:
    src:  "isolinux.cfg.j2"
    dest: "/root/usb_stick/isolinux/isolinux.cfg"
    mode: '0644'

- name: Create qubinode iso image
  become: yes
  shell: >
    /usr/bin/mkisofs
    -allow-limited-size -o usb_stick.iso
    -b isolinux/isolinux.bin
    -c isolinux/boot.cat
    -no-emul-boot 
    -V "qubinode"
    -boot-load-size 4
    -boot-info-table 
    -r -T -J usb_stick && /usr/bin/isohybrid -v /root/usb_stick.iso
  args:
    chdir: /root/

- name: Copy qubinode iso file to usb device
  become: yes
  shell: >
     /usr/bin/cat /root/usb_stick.iso > {{ usb_device }}
    

