---
- name: Check if {{iso_img_file}} exists
  stat: 
    path: "{{iso_dir}}/{{iso_img_file}}"
  register: iso_image_exists
    
- debug:
  var: iso_image_exists

- fail:
    msg: "Whoops! {{iso_img_file}} not found"
  when: iso_image_exists.stat.exists == False

- name: Check if {{iso_boot_file}} exists
  stat: 
    path: "{{iso_dir}}/{{iso_boot_file}}"
  register: iso_boot_exists
    
- debug:
  var: iso_boot_exists

- fail:
    msg: "Whoops! {{iso_boot_file}} not found"
  when: iso_image_exists.stat.exists == False

- name: Check if {{qcow_image_file}} exists
  stat:
    path: "{{iso_dir}}/{{qcow_image_file}}"
  register: qcow_image_exists
    
- debug:
  var: qcow_image_exists

- fail:
    msg: "Whoops! {{qcow_image_file}} not found"
  when: qcow_image_exists.stat.exists == False
  
