---
- name: Install required packages
  become: yes
  yum:
    name:
      - 'genisoimage'
      - 'isomd5sum'
      - 'rsync'
      - 'syslinux'
    state: present
    
- name: Create required mounting directories
  become: yes
  file:
    path: "{{iso_dir}}/usb_stick"
    state: directory

- name: Check if required image file exists
  block:
    - stat: 
      path: "{{iso_dir}}/{{ item }}"
      register: iso_exists
    
    - debug:
      var: iso_exists

    - fail:
      msg: "Whoops! {{ item }} not found"
      when: iso_exists.stat.exists == False
  loop:
   - "{{iso_img_file}}"
   - "{{iso_boot_file}}"
   - "{{qcow_image_file}}"

- name: Mount boot iso file
  become: yes 
  shell: >
    /usr/bin/mount 
    -t iso9660 
    -o loop "{{ iso_boot_file }}"
    /media/

- name: Copy boot iso data to usb_stick directory
  become: yes
  synchronize:
    src: '/media/isolinux'
    dest: '/root/usb_stick'

- name: Copy {{ iso_img_file }} to usb_stick directory
  become: yes
  synchronize:
    src: "{{iso_dir}}/{{iso_img_file}}"
    dest: '/root/usb_stick'
 
- name: Copy RHEL qcow file to usb device
  become: yes
  copy:
    src: "{{iso_dir}}/{{qcow_image_file}}"
    dest: '/root/usb_stick'

 
- name: Copy OCP Cluster Manager pull secret file to usb device
  become: yes
  copy:
    src: "{{iso_dir}}/{{pull_secret_file}}"
    dest: '/root/usb_stick/pull-secret.txt'

- name: Change ownership of usb_stick files and directories
  become: yes
  file:
    path: /root/usb_stick
    mode: 0644
    recurse: true